### ISSUE TITLE
Crash while updating weights

### ISSUE THREAD

**Issue by sceylan** [marsquakeservice/locator#2]
Locator crashes when updating the model weights:

```
15:30:38 [warning] /bin/bash /home/sysop/mars/locator/m_locator.bash error log:
Traceback (most recent call last):
  File "/home/sysop/mars/locator/main.py", line 88, in <module>
    plot_output=args.plot)
  File "/home/sysop/mars/locator/main.py", line 81, in main
    model_names=models)
  File "/home/sysop/mars/locator/locator/output.py", line 93, in write_result
    model_names=model_names)
  File "/home/sysop/mars/locator/locator/output.py", line 172, in _write_h5_output
    model_p_all[weight_bol] = models_p
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3858 but corresponding boolean dimension is 229
```

**Comment by sceylan** [comment]
The crash was on mars-dev. Example input for the crash:

```
velocity_model: MQSORTv2.2018-11-22
velocity_model_uncertainty: 1.5
phases:
 -
   code: P1
   datetime: 2019-01-03T15:09:54.186807Z
   uncertainty_lower: 1
   uncertainty_upper: 1
   uncertainty_model: uniform

 -
   code: S1
   datetime: 2019-01-03T15:18:33.492563Z
   uncertainty_lower: 1
   uncertainty_upper: 1
   uncertainty_model: uniform
```

**Comment by sstaehler** [comment]
Probably an inconsistency between model and weight file
